/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:a5aa704d-6579-4bd4-ac47-35e1d4ce9783",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_bOU88z7Az",
    "aws_user_pools_web_client_id": "6oo2c5vqpdb8qaimssqf0u6r2o",
    "oauth": {}
};


export default awsmobile;
